[package]
name = "bttv-emote-importer"
version = "0.1.1"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
mongodb = "2.3.1"
reqwest = { version = "0.11.13", features = ["json"] }
serde = { version = "1.0.152", features = ["derive"] }
tokio = "1.23.0"
